trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  AWS_REGION: 'us-west-2'
  #EKS_CLUSTER_NAME: 'your-eks-cluster-name'
  AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
  AWS_SECRET_ACCESS_KEY: $(awsSecretAccessKey)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true

  - script: |
      pip install awscli
      pip install --upgrade pip
    displayName: 'Install AWS CLI'
