trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  AWS_REGION: 'us-west-2'
  #EKS_CLUSTER_NAME: 'your-eks-cluster-name'
  AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
  AWS_SECRET_ACCESS_KEY: $(awsSecretAccessKey)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install awscli
      pip install --upgrade pip
    displayName: 'Install AWS CLI'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'your-azure-subscription'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
        aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
        aws configure set default.region $(AWS_REGION)
    displayName: 'Configure AWS CLI'
